language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: EqpSsm64KRR9slKYPw1A+gljxmq0UfLw7CKWfI6aFNaM7VaIQveuXH3TUAbdYNTye7vcSMOtApdNWld0+CEPLcdC6cXWGNMHyrYd+vT3s8mDJXFOBtGHfny9Oy9NwBNHYc9rOPNSw6uqkkOGUKdQremFgnAJ9ZFAJVr4Ro93Dd2BjYldP4rzAqEBKKNZan7ia7SyPynBI3DU1OOIIak9jg21AhATBu3MUWtgrYQj7Yok6qbzE8+H1oY4rtmEJ6Q6K5pJR0QdVo5yXvFpc3ETBzvenzDxU24jGAvSkJFOe4q0tzcvuZMCD69ybder1fHlfJqUEP/gTYqdjG1CWmHvm5qxIWyf1aaagDBqL9tt+UkV0jEu+ww/F7zsklwZf0O56vkbi5GxreIfH/vzbtp7/e+l8PQGnyASiR3q/AFG1QayIBaNeJpL9Kn1TRxTBWGVABTkdo8zjXWvBNyLTD3XO3uscekKxh1IcxtpZ6+WMRDAn/Pwuldpg5r8pt60+GKzDwVVcxCJ1NADQ4FLiQI30m4PI6JhZ6CdWHQVRHtZO+k4dqgFfETywuPXnKUi2yvtIIj2c0C3INnqRRoQ2TdvrOOfwMCQ2yPFOXtTZJ14+LE6d8NpHxL8E1OVrHdseo/3hzGQDa+NuVnKYv7x47AwNdbEJ1r/jQb5PVYX2DG2+G8=
  app: homepage
  on:
    repo: loehx/homepage
